-- Lista de porciones de intercambio (alimentos globales, user_id = null).
-- portion_label = cuánto equivale a UNA porción del grupo.
create unique index if not exists minuta_foods_global_uniq
  on minuta_foods (group_key, nombre) where user_id is null;

insert into minuta_foods (group_key, nombre, portion_label, gramos, extra_group, extra_portions, nota) values
-- ============================================================ CEREALES
  ('cereales','Marraqueta','1 diente',40,null,0,null),
  ('cereales','Hallulla','½ unidad',40,null,0,null),
  ('cereales','Pan de molde','2 rebanadas',50,null,0,null),
  ('cereales','Pan integral','2 rebanadas',50,null,0,null),
  ('cereales','Pan amasado','½ unidad',45,null,0,null),
  ('cereales','Pan pita','1 unidad',45,null,0,null),
  ('cereales','Tortilla de trigo','1 unidad',45,null,0,null),
  ('cereales','Arroz cocido','¾ taza',130,null,0,null),
  ('cereales','Fideos cocidos','¾ taza',130,null,0,null),
  ('cereales','Quinoa cocida','¾ taza',130,null,0,null),
  ('cereales','Cuscús cocido','¾ taza',130,null,0,null),
  ('cereales','Tallarines de arroz cocidos','¾ taza',130,null,0,null),
  ('cereales','Polenta cocida','¾ taza',130,null,0,null),
  ('cereales','Mote cocido','¾ taza',130,null,0,null),
  ('cereales','Papas cocidas','1 taza',200,null,0,null),
  ('cereales','Puré de papas','¾ taza',150,null,0,null),
  ('cereales','Camote cocido','¾ taza',150,null,0,null),
  ('cereales','Choclo','1 taza',165,null,0,null),
  ('cereales','Arvejas cocidas','¾ taza',130,null,0,null),
  ('cereales','Avena','6 cucharadas',45,null,0,null),
  ('cereales','Granola','⅓ taza',40,null,0,'Revisa el azúcar añadido'),
  ('cereales','Cereal de desayuno sin azúcar','1 taza',40,null,0,null),
  ('cereales','Harina tostada','5 cucharadas',40,null,0,null),
  ('cereales','Galletas de agua o soda','6 unidades',40,null,0,null),
  ('cereales','Galletas de arroz','4 unidades',30,null,0,null),
  ('cereales','Barra de cereal','1 unidad',null,null,0,'Ej: Wild Foods'),
  ('cereales','Panqueque o waffle','1 unidad',null,null,0,null),
  ('cereales','Sopaipilla','1 unidad',null,'grasas',1,'Suma además 1 porción de grasa'),
  ('cereales','Miel o azúcar','2 cucharadas',30,null,0,'Preferir evitar'),
  ('cereales','Cerveza (lata 300 cc)','1 lata',null,null,0,'≈140 kcal = 1 cereal. Evitar el alcohol al máximo'),
  ('cereales','Copa de vino','1 copa (140 ml)',null,null,0,'≈140 kcal = 1 cereal. Evitar el alcohol al máximo'),
-- ============================================================== FRUTAS
  ('frutas','Manzana','1 unidad',150,null,0,null),
  ('frutas','Pera','1 unidad',150,null,0,null),
  ('frutas','Plátano','½ unidad',60,null,0,null),
  ('frutas','Kiwi','2 unidades',150,null,0,'2 kiwis 1 hora antes de dormir ayudan al sueño'),
  ('frutas','Mandarina','2 a 3 unidades',180,null,0,null),
  ('frutas','Naranja','1 unidad',180,null,0,null),
  ('frutas','Pomelo','1 unidad',200,null,0,null),
  ('frutas','Uva','15 unidades',120,null,0,null),
  ('frutas','Frutillas','1½ taza',200,null,0,null),
  ('frutas','Arándanos','1 taza',150,null,0,null),
  ('frutas','Frambuesas','1 taza',150,null,0,null),
  ('frutas','Sandía','1½ taza',250,null,0,null),
  ('frutas','Melón','1 taza',200,null,0,null),
  ('frutas','Durazno','1 unidad',150,null,0,null),
  ('frutas','Nectarín','1 unidad',150,null,0,null),
  ('frutas','Ciruela','2 unidades',130,null,0,null),
  ('frutas','Damasco','3 unidades',140,null,0,null),
  ('frutas','Cereza','12 unidades',100,null,0,null),
  ('frutas','Piña','1 taza',150,null,0,null),
  ('frutas','Papaya','1 taza',150,null,0,null),
  ('frutas','Mango','½ unidad',100,null,0,null),
  ('frutas','Chirimoya','½ unidad',100,null,0,null),
  ('frutas','Tuna','2 unidades',150,null,0,null),
  ('frutas','Higo','2 unidades',100,null,0,null),
  ('frutas','Níspero','3 unidades',150,null,0,null),
  ('frutas','Pasas','2 cucharadas',25,null,0,null),
  ('frutas','Jugo de fruta natural','½ taza',120,null,0,'Mejor la fruta entera'),
  ('frutas','Compota sin azúcar','½ taza',120,null,0,null),
-- ============================================================ VERDURAS
  ('verduras','Zapallo italiano','1 taza',150,null,0,null),
  ('verduras','Zanahoria','1 taza',130,null,0,null),
  ('verduras','Betarraga cocida','1 taza',130,null,0,null),
  ('verduras','Brócoli','1 taza',150,null,0,null),
  ('verduras','Coliflor','1 taza',150,null,0,null),
  ('verduras','Porotos verdes','1 taza',150,null,0,null),
  ('verduras','Espinaca cocida','1 taza',150,null,0,null),
  ('verduras','Acelga cocida','1 taza',150,null,0,null),
  ('verduras','Berenjena','1 taza',150,null,0,null),
  ('verduras','Pimentón','1 taza',150,null,0,null),
  ('verduras','Tomate','1 unidad grande',200,null,0,null),
  ('verduras','Cebolla','1 taza',150,null,0,null),
  ('verduras','Champiñones','1 taza',150,null,0,null),
  ('verduras','Repollo cocido','1 taza',150,null,0,null),
  ('verduras','Zapallo','1 taza',150,null,0,null),
  ('verduras','Espárragos','1 taza',150,null,0,null),
  ('verduras','Alcachofa','1 unidad',null,null,0,null),
  ('verduras','Palmitos','1 taza',150,null,0,null),
  ('verduras','Salsa de tomate','1 taza',250,null,0,'Las salsas cuentan como verdura'),
  ('verduras','Verduras salteadas surtidas','1 taza',150,null,0,null),
  ('verduras','Ensalada chilena','1 taza',150,null,0,null),
-- ================================================ VERDURAS LIBRE CONSUMO
  ('verduras_libres','Lechuga','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Apio','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Pepino','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Rabanito','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Rúcula','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Espinaca cruda','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Repollo crudo','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Achicoria o endivia','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Berros','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Brotes de alfalfa','Libre (1 taza)',null,null,0,null),
  ('verduras_libres','Cilantro y perejil','Libre',null,null,0,null),
  ('verduras_libres','Cebollín','Libre',null,null,0,null),
  ('verduras_libres','Ají','Libre',null,null,0,null),
  ('verduras_libres','Limón','Libre',null,null,0,null),
  ('verduras_libres','Aliños, vinagre y especias','Libre',null,null,0,null),
-- =========================================================== PROTEÍNAS
  ('proteinas','Pechuga de pollo cocida','50 g',50,null,0,'≈65 g en crudo'),
  ('proteinas','Pavo cocido','50 g',50,null,0,null),
  ('proteinas','Posta rosada o negra','50 g',50,null,0,null),
  ('proteinas','Filete de vacuno','50 g',50,null,0,null),
  ('proteinas','Carne molida magra','50 g',50,null,0,null),
  ('proteinas','Lomo de cerdo','50 g',50,null,0,null),
  ('proteinas','Merluza','50 g',50,null,0,'Pescado 2 veces por semana'),
  ('proteinas','Reineta','50 g',50,null,0,'Pescado 2 veces por semana'),
  ('proteinas','Salmón','50 g',50,'grasas',1,'Suma además 1 porción de grasa (grasa buena)'),
  ('proteinas','Atún en agua','½ taza',50,null,0,null),
  ('proteinas','Jurel en agua','50 g',50,null,0,null),
  ('proteinas','Sardinas','50 g',50,'grasas',1,null),
  ('proteinas','Camarones','60 g',60,null,0,null),
  ('proteinas','Choritos o mariscos','60 g',60,null,0,null),
  ('proteinas','Huevo entero','1½ unidades',null,null,0,'3 huevos = 2 porciones'),
  ('proteinas','Clara de huevo','4 claras',null,null,0,null),
  ('proteinas','Quesillo','60 g',60,null,0,null),
  ('proteinas','Ricotta','60 g',60,null,0,null),
  ('proteinas','Queso fresco','40 g',40,'grasas',1,null),
  ('proteinas','Jamón de pavo','3 rebanadas',50,null,0,null),
  ('proteinas','Jamón de pierna','50 g',50,null,0,null),
  ('proteinas','Tofu','100 g',100,null,0,null),
  ('proteinas','Proteína en polvo','½ scoop',null,null,0,'1 scoop = 2 porciones de carnes magras'),
  ('proteinas','Barra proteica','½ unidad',null,null,0,'Ej: Wild Foods. 1 barra ≈ 2 porciones'),
  ('proteinas','Lentejas cocidas','¾ taza',130,'cereales',1,'Legumbres 2 veces por semana. Suma 1 cereal'),
  ('proteinas','Garbanzos cocidos','¾ taza',130,'cereales',1,'Legumbres 2 veces por semana. Suma 1 cereal'),
  ('proteinas','Porotos cocidos','¾ taza',130,'cereales',1,'Legumbres 2 veces por semana. Suma 1 cereal'),
  ('proteinas','Arvejas partidas cocidas','¾ taza',130,'cereales',1,'Suma 1 cereal'),
  ('proteinas','Hamburguesa de vacuno','1 unidad',70,'grasas',1,null),
-- ============================================================= LÁCTEOS
  ('lacteos','Leche semidescremada','200 cc',200,null,0,null),
  ('lacteos','Leche sin lactosa','200 cc',200,null,0,null),
  ('lacteos','Leche descremada en polvo','3 cucharadas',30,null,0,null),
  ('lacteos','Leche cultivada','200 cc',200,null,0,null),
  ('lacteos','Kéfir','200 cc',200,null,0,null),
  ('lacteos','Yogur natural o light','1 unidad',150,null,0,null),
  ('lacteos','Yogur griego sin azúcar','1 unidad',150,null,0,null),
  ('lacteos','Yogur proteico','1 unidad',150,null,0,'Ej: Colun Protein, Dos Álamos'),
  ('lacteos','Bebida de soya','200 cc',200,null,0,'Menos proteína que la leche'),
-- ============================================================== GRASAS
  ('grasas','Aceite de oliva','1 cucharadita',5,null,0,null),
  ('grasas','Aceite de canola o maravilla','1 cucharadita',5,null,0,null),
  ('grasas','Palta','30 g (⅛ unidad)',30,null,0,null),
  ('grasas','Mayonesa','1 cucharadita',5,null,0,'La light rinde el doble'),
  ('grasas','Mantequilla de maní','1 cucharadita',5,null,0,null),
  ('grasas','Mantequilla o margarina','1 cucharadita',5,null,0,null),
  ('grasas','Crema','1 cucharada',15,null,0,null),
  ('grasas','Queso crema','1 cucharada',15,null,0,null),
  ('grasas','Nueces','3 mitades',7,null,0,null),
  ('grasas','Almendras','6 unidades',7,null,0,null),
  ('grasas','Maní','10 unidades',8,null,0,null),
  ('grasas','Castañas de cajú','6 unidades',8,null,0,null),
  ('grasas','Pistachos','12 unidades',8,null,0,null),
  ('grasas','Semillas de chía','1 cucharada',10,null,0,null),
  ('grasas','Linaza molida','1 cucharada',10,null,0,null),
  ('grasas','Semillas de zapallo','1 cucharada',10,null,0,null),
  ('grasas','Aceitunas','8 unidades',40,null,0,null),
  ('grasas','Coco rallado','2 cucharadas',10,null,0,null),
  ('grasas','Tahini','1 cucharadita',5,null,0,null),
  ('grasas','Aderezo tipo césar','1 cucharada',15,null,0,null)
on conflict (group_key, nombre) where user_id is null do update set
  portion_label = excluded.portion_label,
  gramos        = excluded.gramos,
  extra_group   = excluded.extra_group,
  extra_portions= excluded.extra_portions,
  nota          = excluded.nota;
